# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_simple.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1240, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text = QtWidgets.QPlainTextEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.text.setFont(font)
        self.text.setReadOnly(True)
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.text.setPlainText(_translate("Dialog", "Функции приложения:\n"
" + Данное приложение позволяет по названию модели устройства одновременно искать данные в *.xml прайсе и интернет базе.\n"
"\n"
"Особенности:\n"
" + Убирает необходимость искать одно и то же в прайсе и в браузере.\n"
" + Убирает необходимость выбирать лист прайса и искать модель визуально.\n"
" + Быстрый поиск почти не трогая мышь. Переключаешься на приложение -> вводишь модель -> жмешь энтер -> результат.\n"
" - Проводить квитанции надо через сайт, но это нужно реже.\n"
" - Не удалось нейтрализовать все косяки прайса (например iPad), вопросы к составителю, все листы разные с разными приколами.\n"
" - Не поддерживается Windows XP и ниже :(\n"
"\n"
"Использование:\n"
"Прайс должен иметь формат *Прийс*.xml и находиться на рабочем столе.\n"
"При первом запуске зайдите в настройки приложения и введите ваши Логин и Пароль от интернет базы.\n"
"При переключении на приложение можно сразу вводить модель, выделять посковую строку не обязательно.\n"
"В процессе ввода производится поиск в прайсе и найденные модели выводятся в виде кнопок в правом верхнем углу.\n"
"    Стрелки вверх/вниз - выбор модели из списка.\n"
"    Enter/Click - вывод данных прайса/базы.\n"
"    Alt - переключение таблиц Запчасти/Аксессуары\n"
"    При наведение на поле таблицы появляется подсказка с полным ее содержимым.\n"
"    При двойном клике по строке таблицы Запчасти/Аксессуары часть полей копируется и подчеркивается.\n"
"        Скопированную строку можно использовать для заказа.\n"
"\n"
"    \"Строго\" - поиск начиная с 2х символов. Отключите, если надо найти один симвор (например кириллическую \"с\").\n"
"    \"Латиница\" - ввод латинских символов вне зависимости от текущей раскладки. - В РАЗРАБОТКЕ (не реализовано)\n"
"    \"Умный поиск\" - фильтрует данные, если чего-то не находите, попробуйте отключить. - В РАЗРАБОТКЕ (всегда активно)\n"
"    \"Показать лист\" - отображает весь лист из прайса. Необходимо, если поиск не сработал. - В РАЗРАБОТКЕ (не реализовано)\n"
"\n"
"В настройках можно изменить шрифт и прочее под свой монитор\n"
"\n"
"\n"
"Программа улучшается в свободное время."))
