# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_graphs.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1240, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 38))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_by_branches = QtWidgets.QCheckBox(self.frame_2)
        self.cb_by_branches.setObjectName("cb_by_branches")
        self.horizontalLayout_3.addWidget(self.cb_by_branches)
        self.cb_year = QtWidgets.QComboBox(self.frame_2)
        self.cb_year.setMinimumSize(QtCore.QSize(120, 0))
        self.cb_year.setMaximumSize(QtCore.QSize(120, 28))
        self.cb_year.setBaseSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_year.setFont(font)
        self.cb_year.setMaxVisibleItems(12)
        self.cb_year.setObjectName("cb_year")
        self.horizontalLayout_3.addWidget(self.cb_year)
        self.cb_month = QtWidgets.QComboBox(self.frame_2)
        self.cb_month.setMinimumSize(QtCore.QSize(120, 0))
        self.cb_month.setMaximumSize(QtCore.QSize(120, 28))
        self.cb_month.setBaseSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_month.setFont(font)
        self.cb_month.setMaxVisibleItems(12)
        self.cb_month.setObjectName("cb_month")
        self.horizontalLayout_3.addWidget(self.cb_month)
        self.rb_year = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_year.setFont(font)
        self.rb_year.setObjectName("rb_year")
        self.horizontalLayout_3.addWidget(self.rb_year)
        self.rb_month = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_month.setFont(font)
        self.rb_month.setObjectName("rb_month")
        self.horizontalLayout_3.addWidget(self.rb_month)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_2)
        self.graph_frame = QtWidgets.QFrame(Dialog)
        self.graph_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.graph_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graph_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.graph_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.graph_frame.setObjectName("graph_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.graph_frame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addWidget(self.graph_frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cb_by_branches.setText(_translate("Dialog", "Отделения"))
        self.rb_year.setText(_translate("Dialog", "Год"))
        self.rb_month.setText(_translate("Dialog", "Месяц"))
